# Generated by Django 4.1.6 on 2023-02-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo_espacial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculolanzadera',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculonotripulado',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculotripulado',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
