# Generated by Django 4.1.6 on 2023-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo_espacial', '0004_alter_vehiculolanzadera_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculolanzadera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculonotripulado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiculotripulado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
